[package]
name = "resplit"
version = "0.1.0"
edition = "2021"
author = "Alfredo Deza <alfredo@deza.pe>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["derive"] }
